---
title: Poképedia
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: benningtonkids9@gmail.com
description: Gotta read 'em all!
encoding: utf-8
locale: en-AU
baseurl: 
markdown: kramdown
highlighter: rouge
markdown_ext: md,markdown,mkdown,mkdn,mkd
permalink: pretty
plugins:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
